# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-11 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('solution', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
